'use strict';function z(f,a,b,d){f.A.pc(f.ab,a,b,d,void 0)}function H(f,a,b,d){f.A.ca?z(f,a,b,d):f.A.hf()._OnMessageFromDOM({type:"event",component:f.ab,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function J(f,a,b){f.A.C(f.ab,a,b)}function K(f,a){for(const [b,d]of a)J(f,b,d)}function M(f){f.Rb||(f.A.Te(f.ce),f.Rb=!0)}window.Sa=class{constructor(f,a){this.A=f;this.ab=a;this.Rb=!1;this.ce=()=>this.Da()}dd(){}Da(){}};function N(f){-1!==f.Pa&&(self.clearTimeout(f.Pa),f.Pa=-1)}
window.Ke=class{constructor(f,a){this.Kc=f;this.xg=a;this.Pa=-1;this.Tb=-Infinity;this.de=()=>{this.Pa=-1;this.Tb=Date.now();this.gb=!0;this.Kc();this.gb=!1};this.Md=this.gb=!1}c(){N(this);this.de=this.Kc=null}};"use strict";function O(f,a){const b=a.elementId,d=f.hd(a);f.Y.set(b,d);a.isVisible||(d.style.display="none");d.addEventListener("focus",()=>{P(f,"elem-focused",b)});d.addEventListener("blur",()=>{P(f,"elem-blurred",b)});f.Mb&&document.body.appendChild(d)}
function Q(f,a,b){J(f,a,d=>{const g=f.Y.get(d.elementId);return b(g,d)})}function P(f,a,b){var d;d||(d={});d.elementId=b;z(f,a,d)}
window.we=class extends self.Sa{constructor(f,a){super(f,a);this.Y=new Map;this.Mb=!0;K(this,[["create",b=>O(this,b)],["destroy",b=>{{b=b.elementId;const d=this.Y.get(b);this.kd(d);this.Mb&&d.parentElement.removeChild(d);this.Y.delete(b)}}],["set-visible",b=>{this.Mb&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Mb){var d=this.Y.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=b.height+"px";
b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.Y.get(b.elementId);this.td()}],["focus",b=>{{const d=this.Y.get(b.elementId);b.focus?d.focus():d.blur()}}],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);Q(this,"get-element",b=>b)}hd(){throw Error("required override");}kd(){}td(){throw Error("required override");
}};"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(m){const c=document.createElement("script");c.async=!1;c.type="module";return m.Ig?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;c.textContent=m.Mg+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=m;document.head.appendChild(c)})}let d=!1,g=!1;function n(){if(!d){try{new Worker("blob://",{get type(){g=!0}})}catch(m){}d=!0}return g}const q=
/safari\//i.test(navigator.userAgent)&&!/chrome\/|chromium\/|edg\//i.test(navigator.userAgent);let v=new Audio;const B={"audio/webm; codecs=opus":!!v.canPlayType("audio/webm; codecs=opus")&&!q,"audio/ogg; codecs=opus":!!v.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!v.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!v.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!v.canPlayType("audio/mp4"),"audio/mpeg":!!v.canPlayType("audio/mpeg")};v=null;async function D(m){m=
await w(m);return(new TextDecoder("utf-8")).decode(m)}function w(m){return new Promise((c,k)=>{const l=new FileReader;l.onload=p=>c(p.target.result);l.onerror=p=>k(p);l.readAsArrayBuffer(m)})}const x=[];let C=0;window.RealFile=window.File;const E=[],A=new Map,F=new Map;let I=0;const L=[];self.runOnStartup=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");L.push(m)};const e=new Set(["cordova","playable-ad","instant-games"]);let h=!1;window.Ca=class m{constructor(c){this.ca=
c.Og;this.oa=null;this.F="";this.cc=c.Lg;this.vb={};this.Ia=this.ub=null;this.Pb=[];this.jb=this.K=this.Na=null;this.Ma=-1;this.Cg=()=>this.Hf();this.La=[];this.v=c.ee;this.hb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&n()||(this.ca=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ca=!1;if("cordova"===this.v&&this.ca)if(/android/i.test(navigator.userAgent)){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],
10)||(this.ca=!1)}else this.ca=!1;this.Vb=this.ha=null;"html5"!==this.v&&"playable-ad"!==this.v||!this.hb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.C("runtime","cordova-fetch-local-file",k=>this.rf(k));this.C("runtime","create-job-worker",()=>this.sf());"cordova"===this.v?document.addEventListener("deviceready",()=>this.yd(c)):this.yd(c)}c(){this.vc();this.oa&&(this.oa=this.oa.onmessage=
null);this.ub&&(this.ub.terminate(),this.ub=null);this.Ia&&(this.Ia.c(),this.Ia=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}Fe(){return f&&"cordova"===this.v}oc(){const c=navigator.userAgent;return f&&e.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}async yd(c){"macos-wkwebview"===this.v&&this.$f();if("playable-ad"===this.v){this.ha=self.c3_base64files;this.Vb={};await this.Ye();for(let l=0,p=c.Qa.length;l<p;++l){var k=c.Qa[l].toLowerCase();this.Vb.hasOwnProperty(k)?
c.Qa[l]={Ig:!0,Mg:this.Vb[k]}:this.ha.hasOwnProperty(k)&&(c.Qa[l]=URL.createObjectURL(this.ha[k]))}}c.Dg?this.F=c.Dg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));c.Qg&&(this.vb=c.Qg);k=new MessageChannel;this.oa=k.port1;this.oa.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Df(l));this.jb=new self.Ge(this);await R(this.jb);"object"===typeof window.StatusBar&&
window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ca?await this.kf(c,k.port2):await this.jf(c,k.port2)}yc(c){c=this.vb.hasOwnProperty(c)?this.vb[c]:c.endsWith("/workermain.js")&&this.vb.hasOwnProperty("workermain.js")?this.vb["workermain.js"]:"playable-ad"===this.v&&this.ha.hasOwnProperty(c.toLowerCase())?this.ha[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async ic(c,k,l){if(c.startsWith("blob:"))return new Worker(c,
l);if("cordova"===this.v&&this.hb)return c=await this.wb(l.Hg?c:this.cc+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}va(){return Math.max(window.innerWidth,1)}ua(){return Math.max(window.innerHeight,1)}xd(c){var k=this.jb;return{baseUrl:this.F,windowInnerWidth:this.va(),
windowInnerHeight:this.ua(),devicePixelRatio:window.devicePixelRatio,isFullscreen:m.Va(),projectData:c.Vg,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Tg||"",exportType:c.ee,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Ug,jobScheduler:{inputPort:k.Qc,outputPort:k.Xc,maxNumWorkers:k.zg},supportedAudioFormats:B,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||
this.cc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.cc+"opus.wasm.wasm",isFileProtocol:this.hb,isiOSCordova:this.Fe(),isiOSWebView:this.oc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async kf(c,k){var l=this.yc(c.Pg);this.ub=await this.ic(l,this.F,{type:"module",name:"Runtime",Hg:!0});this.K=document.createElement("canvas");this.K.style.display="none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);window.c3canvas=this.K;let p=c.cd||[],
u=c.Qa;p=await Promise.all(p.map(r=>this.Ea(r)));u=await Promise.all(u.map(r=>this.Ea(r)));if("cordova"===this.v)for(let r=0,t=c.fc.length;r<t;++r){const y=c.fc[r],G=y[0];if(G===c.ad||"scriptsInEvents.js"===G||G.endsWith("/scriptsInEvents.js"))y[1]=await this.Ea(G)}this.ub.postMessage(Object.assign(this.xd(c),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:p,engineScripts:u,projectScripts:c.fc,mainProjectScript:c.ad,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[k,l,...S(this.jb)]);this.Pb=E.map(r=>new r(this));this.wd();self.c3_callFunction=(r,t)=>this.Na.lf(r,t);"preview"===this.v&&(self.goToLastErrorScript=()=>this.pc("runtime","go-to-last-error-script"))}async jf(c,k){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Pb=E.map(r=>new r(this));this.wd();var l=c.Qa.map(r=>"string"===typeof r?(new URL(r,this.F)).toString():r);Array.isArray(c.cd)&&l.unshift(...c.cd);l=await Promise.all(l.map(r=>
this.Ea(r)));await Promise.all(l.map(r=>b(r)));l=self.C3_ProjectScriptsStatus;const p=c.ad,u=c.fc;for(let [r,t]of u)if(t||(t=r),r===p)try{t=await this.Ea(t),await b(t),"preview"!==this.v||l[r]||this.Gd(r,"main script did not run to completion")}catch(y){this.Gd(r,y)}else if("scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))t=await this.Ea(t),await b(t);"preview"===this.v&&"object"!==typeof self.Rg.Sg?(this.Ib(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.xd(c),{isInWorker:!1,messagePort:k,canvas:this.K,runOnStartupFunctions:L}),this.Ad(),this.Ia=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ia,c))}Gd(c,k){this.Ib();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ad(){this.Ib()}Ib(){const c=
window.Eg;c&&(c.parentElement.removeChild(c),window.Eg=null)}async sf(){const c=await T(this.jb);return{outputPort:c,transferables:[c]}}hf(){if(this.ca)throw Error("not available in worker mode");return this.Ia}pc(c,k,l,p,u){this.oa.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:null},u)}od(c,k,l,p,u){const r=I++,t=new Promise((y,G)=>{F.set(r,{resolve:y,reject:G})});this.oa.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:r},
u);return t}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.xf(c);if("result"===k)this.Kf(c);else if("runtime-ready"===k)this.Lf();else if("alert-error"===k)this.Ib(),alert(c.message);else if("creating-runtime"===k)this.Ad();else throw Error(`unknown message '${k}'`);}xf(c){const k=c.component,l=c.handler,p=c.data,u=c.responseId;if(c=A.get(k))if(c=c.get(l)){var r=null;try{r=c(p)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==u&&this.Hb(u,!1,""+t);return}if(null===
u)return r;r&&r.then?r.then(t=>this.Hb(u,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Hb(u,!1,""+t)}):this.Hb(u,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Hb(c,k,l){let p;l&&l.transferables&&(p=l.transferables);this.oa.postMessage({type:"result",responseId:c,isOk:k,result:l},p)}Kf(c){const k=c.responseId,l=c.isOk;c=c.result;const p=F.get(k);l?p.resolve(c):p.reject(c);F.delete(k)}C(c,
k,l){let p=A.get(c);p||(p=new Map,A.set(c,p));if(p.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);p.set(k,l)}static Ra(c){if(E.includes(c))throw Error("DOM handler already added");E.push(c)}wd(){for(const c of this.Pb)if("runtime"===c.ab){this.Na=c;return}throw Error("cannot find runtime DOM handler");}Df(c){this.pc("debugger","message",c)}Lf(){for(const c of this.Pb)c.dd()}static Va(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
h)}static Hd(c){h=!!c}Te(c){this.La.push(c);this.Ic()}Xf(c){c=this.La.indexOf(c);if(-1===c)throw Error("invalid callback");this.La.splice(c,1);this.La.length||this.vc()}Ic(){-1===this.Ma&&this.La.length&&(this.Ma=requestAnimationFrame(this.Cg))}vc(){-1!==this.Ma&&(cancelAnimationFrame(this.Ma),this.Ma=-1)}Hf(){this.Ma=-1;for(const c of this.La)c();this.Ic()}ta(c){this.Na.ta(c)}Ba(c){this.Na.Ba(c)}Hc(){this.Na.Hc()}Cb(c){this.Na.Cb(c)}Ee(){return!!B["audio/webm; codecs=opus"]}async vg(c){c=await this.od("runtime",
"opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}De(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}nd(c){return!this.De(c)}async Ea(c){return"cordova"===this.v&&(c.startsWith("file:")||this.hb&&this.nd(c))?(c.startsWith(this.F)&&(c=c.substr(this.F.length)),c=await this.wb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async rf(c){const k=c.filename;switch(c.as){case "text":return await this.ve(k);case "buffer":return await this.wb(k);
default:throw Error("unsupported type");}}gd(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,p)=>{window.resolveLocalFileSystemURL(k,u=>{u.file(l,p)},p)})}async ve(c){c=await this.gd(c);return await D(c)}wc(){if(x.length&&!(8<=C)){C++;var c=x.shift();this.Ze(c.filename,c.Ng,c.Gg)}}wb(c){return new Promise((k,l)=>{x.push({filename:c,Ng:p=>{C--;this.wc();k(p)},Gg:p=>{C--;this.wc();l(p)}});this.wc()})}async Ze(c,k,l){try{const p=await this.gd(c),u=await w(p);
k(u)}catch(p){l(p)}}$f(){var c={type:"ready"};if("windows-webview2"===this.v)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.v)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async Ye(){const c=[];for(const [k,l]of Object.entries(this.ha))c.push(this.Xe(k,l));await Promise.all(c)}async Xe(c,k){if("object"===typeof k)this.ha[c]=new Blob([k.str],{type:k.type}),this.Vb[c]=k.str;else{let l=await this.ff(k);
l||(l=this.af(k));this.ha[c]=l}}async ff(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}af(c){c=this.Rf(c);return this.We(c.data,c.Jg)}Rf(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);k=c.substring(5,k).split(";");c=k[0]||
"";const p=k[2];l="base64"===k[1]||"base64"===p?atob(l):decodeURIComponent(l);return{Jg:c,data:l}}We(c,k){var l=c.length;let p=l>>2,u=new Uint8Array(l),r=new Uint32Array(u.buffer,0,p),t,y;for(y=t=0;t<p;++t)r[t]=c.charCodeAt(y++)|c.charCodeAt(y++)<<8|c.charCodeAt(y++)<<16|c.charCodeAt(y++)<<24;for(l&=3;l--;)u[y]=c.charCodeAt(y),++y;return new Blob([u],{type:k})}}}"use strict";
{const f=self.Ca;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(e){return new Promise((h,m)=>{const c=document.createElement("link");c.onload=()=>h(c);c.onerror=k=>m(k);c.rel=
"stylesheet";c.href=e;document.head.appendChild(c)})}function v(e){return new Promise((h,m)=>{const c=new Image;c.onload=()=>h(c);c.onerror=k=>m(k);c.src=e})}async function B(e){e=URL.createObjectURL(e);try{return await v(e)}finally{URL.revokeObjectURL(e)}}function D(e){return new Promise((h,m)=>{let c=new FileReader;c.onload=k=>h(k.target.result);c.onerror=k=>m(k);c.readAsText(e)})}async function w(e,h,m){if(!/firefox/i.test(navigator.userAgent))return await B(e);var c=await D(e);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const k=c.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),p=k.getAttribute("height");if(!l.includes("%")&&!p.includes("%"))return await B(e)}k.setAttribute("width",h+"px");k.setAttribute("height",m+"px");c=(new XMLSerializer).serializeToString(c);e=new Blob([c],{type:"image/svg+xml"});return await B(e)}function x(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),E=new Set(["canvas","body","html"]);function A(e){E.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function F(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await B(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(e,h,m,c,k){e=await w(e,h,m);const l=document.createElement("canvas");l.width=c;l.height=k;l.getContext("2d").drawImage(e,0,0,h,m);return l};let I=!1;document.addEventListener("pause",()=>I=!0);document.addEventListener("resume",()=>I=!1);function L(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}f.Ra(class extends self.Sa{constructor(e){super(e,"runtime");this.Rd=!0;this.Oa=-1;this.Zc="any";this.Id=this.Jd=!1;this.Tc=
this.rb=this.xa=null;e.C("canvas","update-size",c=>this.Of(c));e.C("runtime","invoke-download",c=>this.Bf(c));e.C("runtime","raster-svg-image",c=>this.If(c));e.C("runtime","get-svg-image-size",c=>this.zf(c));e.C("runtime","set-target-orientation",c=>this.Mf(c));e.C("runtime","register-sw",()=>this.Jf());e.C("runtime","post-to-debugger",c=>this.Cd(c));e.C("runtime","go-to-script",c=>this.Cd(c));e.C("runtime","before-start-ticking",()=>this.qf());e.C("runtime","debug-highlight",c=>this.tf(c));e.C("runtime",
"enable-device-orientation",()=>this.Ve());e.C("runtime","enable-device-motion",()=>this.Ue());e.C("runtime","add-stylesheet",c=>this.nf(c));e.C("runtime","alert",c=>this.pf(c));e.C("runtime","hide-cordova-splash",()=>this.Af());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const k=c.target;h.has(k.tagName.toLowerCase())||x(k)||c.preventDefault()});const m=e.K;window.addEventListener("selectstart",A);window.addEventListener("gesturehold",A);m.addEventListener("selectstart",
A);m.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),m.addEventListener("pointerdown",A)):m.addEventListener("touchstart",A);this.ob=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",F,{passive:!1});window.addEventListener("wheel",F,{passive:!1});window.addEventListener("resize",()=>this.Pf());window.addEventListener("fullscreenchange",
()=>this.Xa());window.addEventListener("webkitfullscreenchange",()=>this.Xa());window.addEventListener("mozfullscreenchange",()=>this.Xa());window.addEventListener("fullscreenerror",c=>this.Dc(c));window.addEventListener("webkitfullscreenerror",c=>this.Dc(c));window.addEventListener("mozfullscreenerror",c=>this.Dc(c));e.oc()&&window.addEventListener("focusout",()=>{{const l=document.activeElement;if(l){var c=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));
c="textarea"===c?!0:"input"===c?k.has(l.type.toLowerCase()||"text"):x(l)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>this.Qf(c);this.Ja=new Set;this.Wb=new WeakSet;this.na=!1}qf(){"cordova"===this.A.v?(document.addEventListener("pause",()=>this.Gc(!0)),document.addEventListener("resume",()=>this.Gc(!1))):document.addEventListener("visibilitychange",()=>this.Gc(document.hidden));return{isSuspended:!(!document.hidden&&!I)}}dd(){window.addEventListener("focus",()=>
this.Za("window-focus"));window.addEventListener("blur",()=>{this.Za("window-blur",{parentHasFocus:L()});this.ob=0});window.addEventListener("focusin",h=>{h=h.target;(C.has(h.tagName.toLowerCase())||x(h))&&this.Za("keyboard-blur")});window.addEventListener("keydown",h=>this.Bd("keydown",h));window.addEventListener("keyup",h=>this.Bd("keyup",h));window.addEventListener("dblclick",h=>this.Ec("dblclick",h,d));window.addEventListener("wheel",h=>this.Ff(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.zc(h);this.Ya("pointerdown",h)}),this.A.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.rb=new self.Ke(()=>this.df(),5),this.rb.Md=!0,window.addEventListener("pointerrawupdate",h=>this.Gf(h))):window.addEventListener("pointermove",h=>this.Ya("pointermove",h)),window.addEventListener("pointerup",h=>this.Ya("pointerup",h)),window.addEventListener("pointercancel",h=>this.Ya("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.zc(h);this.Fc("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Fc("pointermove",h)),window.addEventListener("mouseup",h=>this.Fc("pointerup",h)),window.addEventListener("touchstart",h=>{this.zc(h);this.Gb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Gb("pointermove",h)),window.addEventListener("touchend",h=>this.Gb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Gb("pointercancel",h)));const e=()=>this.Hc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",
e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}Za(e,h){z(this,e,h||null,n)}va(){return this.A.va()}ua(){return this.A.ua()}Pf(){const e=this.va(),h=this.ua();this.Za("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Va()});this.A.oc()&&(-1!==this.Oa&&clearTimeout(this.Oa),this.Dd(e,h,0))}Yf(e,h,m){-1!==this.Oa&&clearTimeout(this.Oa);this.Oa=setTimeout(()=>this.Dd(e,
h,m),48)}Dd(e,h,m){const c=this.va(),k=this.ua();this.Oa=-1;c!=e||k!=h?this.Za("window-resize",{innerWidth:c,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Va()}):10>m&&this.Yf(c,k,m+1)}Mf(e){this.Zc=e.targetOrientation}rg(){const e=this.Zc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):screen.webkitLockOrientation?
h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Xa(){const e=f.Va();e&&"any"!==this.Zc&&this.rg();z(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.va(),innerHeight:this.ua()})}Dc(e){console.warn("[Construct 3] Fullscreen request failed: ",e);z(this,"fullscreenerror",
{isFullscreen:f.Va(),innerWidth:this.va(),innerHeight:this.ua()})}Gc(e){e?this.A.vc():this.A.Ic();z(this,"visibilitychange",{hidden:e})}Bd(e,h){"Backspace"===h.key&&A(h);const m=b.get(h.code)||h.code;H(this,e,{code:m,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},d)}Ff(e){z(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,
timeStamp:e.timeStamp},d)}Ec(e,h,m){a(h)||H(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},m)}Fc(e,h){if(!a(h)){var m=this.ob;"pointerdown"===e&&0!==m?e="pointermove":"pointerup"===e&&0!==h.buttons&&(e="pointermove");H(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},d);this.ob=h.buttons;this.Ec(h.type,h,g)}}Ya(e,h){if(this.rb&&"pointermove"!==e){var m=this.rb;m.gb||(N(m),m.Tb=Date.now())}m=0;"mouse"===h.pointerType&&(m=this.ob);H(this,e,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,
tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},d);"mouse"===h.pointerType&&(m="mousemove","pointerdown"===e?m="mousedown":"pointerup"===e&&(m="mouseup"),this.Ec(m,h,g),this.ob=h.buttons)}Gf(e){this.Tc=e;e=this.rb;if(-1===e.Pa){var h=Date.now(),m=h-e.Tb,c=e.xg;m>=c&&e.Md?(e.Tb=h,e.gb=!0,e.Kc(),e.gb=!1):e.Pa=self.setTimeout(e.de,Math.max(c-m,4))}}df(){this.Ya("pointermove",this.Tc);this.Tc=null}Gb(e,h){for(let m=0,c=h.changedTouches.length;m<c;++m){const k=h.changedTouches[m];H(this,e,{pointerId:k.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:2*(k.radiusX||k.webkitRadiusX||0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:h.timeStamp},d)}}zc(e){window!==window.top&&window.focus();this.zd(e.target)&&document.activeElement&&!this.zd(document.activeElement)&&document.activeElement.blur()}zd(e){return!e||e===document||
e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}Ve(){this.Jd||(this.Jd=!0,window.addEventListener("deviceorientation",e=>this.vf(e)),window.addEventListener("deviceorientationabsolute",e=>this.wf(e)))}Ue(){this.Id||(this.Id=!0,window.addEventListener("devicemotion",e=>this.uf(e)))}vf(e){z(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},
d)}wf(e){z(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}uf(e){let h=null;var m=e.acceleration;m&&(h={x:m.x||0,y:m.y||0,z:m.z||0});m=null;var c=e.accelerationIncludingGravity;c&&(m={x:c.x||0,y:c.y||0,z:c.z||0});c=null;const k=e.rotationRate;k&&(c={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});z(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:m,rotationRate:c,interval:e.interval,timeStamp:e.timeStamp},
d)}Of(e){const h=this.A.K;h.style.width=e.styleWidth+"px";h.style.height=e.styleHeight+"px";h.style.marginLeft=e.marginLeft+"px";h.style.marginTop=e.marginTop+"px";this.Rd&&(h.style.display="",this.Rd=!1)}Bf(e){const h=e.url;e=e.filename;const m=document.createElement("a"),c=document.body;m.textContent=e;m.href=h;m.download=e;c.appendChild(m);m.click();c.removeChild(m)}async If(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);
h=h?await createImageBitmap(e,h):await createImageBitmap(e);return{imageBitmap:h,transferables:[h]}}async zf(e){return await self.C3_GetSvgImageSize(e.blob)}async nf(e){await q(e.url)}Hc(){var e=[...this.Ja];this.Ja.clear();if(!this.na)for(const h of e)(e=h.play())&&e.catch(()=>{this.Wb.has(h)||this.Ja.add(h)})}ta(e){if("function"!==typeof e.play)throw Error("missing play function");this.Wb.delete(e);let h;try{h=e.play()}catch(m){this.Ja.add(e);return}h&&h.catch(()=>{this.Wb.has(e)||this.Ja.add(e)})}Ba(e){this.Ja.delete(e);
this.Wb.add(e)}Cb(e){this.na=!!e}Af(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}tf(e){if(e.show){this.xa||(this.xa=document.createElement("div"),this.xa.id="inspectOutline",document.body.appendChild(this.xa));var h=this.xa;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.xa&&(this.xa.style.display="none")}Jf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Cd(e){window.c3_postToMessagePort&&
(e.from="runtime",window.c3_postToMessagePort(e))}lf(e,h){return this.A.od(this.ab,"js-invoke-function",{name:e,params:h},void 0,void 0)}pf(e){alert(e.message)}Qf(e){"entered-fullscreen"===e?(f.Hd(!0),this.Xa()):"exited-fullscreen"===e?(f.Hd(!1),this.Xa()):console.warn("Unknown wrapper message: ",e)}})}"use strict";
async function R(f){if(f.wg)throw Error("already initialised");f.wg=!0;var a=f.bc.yc("dispatchworker.js");f.Mc=await f.bc.ic(a,f.F,{name:"DispatchWorker"});a=new MessageChannel;f.Qc=a.port1;f.Mc.postMessage({type:"_init","in-port":a.port2},[a.port2]);f.Xc=await T(f)}function S(f){return[f.Qc,f.Xc]}
async function T(f){const a=f.Sd.length;var b=f.bc.yc("jobworker.js");b=await f.bc.ic(b,f.F,{name:"JobWorker"+a});const d=new MessageChannel,g=new MessageChannel;f.Mc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":g.port2},[d.port2,g.port2]);f.Sd.push(b);return g.port1}
self.Ge=class{constructor(f){this.bc=f;this.F=f.F;this.F="preview"===f.v?this.F+"workers/":this.F+f.cc;this.zg=Math.min(navigator.hardwareConcurrency||2,16);this.Mc=null;this.Sd=[];this.Xc=this.Qc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Ca({Og:!0,Pg:"workermain.js",Qa:["scripts/c3runtime.js"],fc:[],ad:"",Lg:"scripts/",cd:[],ee:"html5"}));"use strict";
self.Ca.Ra(class extends self.Sa{constructor(f){super(f,"mouse");J(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";
{const f=180/Math.PI;self.da=class extends self.Sa{constructor(a){super(a,"audio");this.Ob=this.f=null;this.Qb=this.Pc=!1;this.qa=()=>this.sg();this.aa=[];this.D=[];this.ga=null;this.Td="";this.Ud=-1;this.qb=new Map;this.Uc=1;this.na=!1;this.$c=0;this.dc=1;this.Nc=0;this.Wd="HRTF";this.Nd="inverse";this.Xd=600;this.Vd=1E4;this.Zd=1;this.Pd=this.Yc=!1;this.be=this.A.Ee();this.ba=new Map;this.Ga=new Set;this.Rc=!1;this.Vc="";this.ya=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Ef(b,d);this.Nb=null;
self.C3Audio_GetOutputStream=()=>this.yf();self.C3Audio_DOMInterface=this;K(this,[["create-audio-context",b=>this.$e(b)],["play",b=>this.Sf(b)],["stop",b=>this.pg(b)],["stop-all",()=>this.qg()],["set-paused",b=>this.ig(b)],["set-volume",b=>this.ng(b)],["fade-volume",b=>this.ef(b)],["set-master-volume",b=>this.gg(b)],["set-muted",b=>this.hg(b)],["set-silent",b=>this.kg(b)],["set-looping",b=>this.fg(b)],["set-playback-rate",b=>this.jg(b)],["seek",b=>this.Zf(b)],["preload",b=>this.Tf(b)],["unload",b=>
this.tg(b)],["unload-all",()=>this.ug()],["set-suspended",b=>this.lg(b)],["add-effect",b=>this.ud(b)],["set-effect-param",b=>this.cg(b)],["remove-effects",b=>this.Vf(b)],["tick",b=>this.Nf(b)],["load-state",b=>this.Cf(b)]])}async $e(a){a.isiOSCordova&&(this.Yc=!0);this.$c=a.timeScaleMode;this.Wd=["equalpower","HRTF","soundfield"][a.panningModel];this.Nd=["linear","inverse","exponential"][a.distanceModel];this.Xd=a.refDistance;this.Vd=a.maxDistance;this.Zd=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.be||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.vd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.vd()};this.Ob=this.f.createGain();this.Ob.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.jc();try{await Promise.all(a.preloadList.map(d=>this.Eb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}vd(){this.Qb||(this.Pc=!1,window.addEventListener("pointerup",this.qa,!0),window.addEventListener("touchend",this.qa,!0),window.addEventListener("click",this.qa,!0),window.addEventListener("keydown",this.qa,!0),this.Qb=!0)}bf(){this.Qb&&(this.Pc=!0,window.removeEventListener("pointerup",this.qa,!0),window.removeEventListener("touchend",
this.qa,!0),window.removeEventListener("click",this.qa,!0),window.removeEventListener("keydown",this.qa,!0),this.Qb=!1)}sg(){if(!this.Pc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.bf()}}W(){return this.f}jc(){return this.f.currentTime}ra(){return this.Ob}ld(a){return(a=this.ba.get(a.toLowerCase()))?a[0].P():this.ra()}fe(a,b){a=a.toLowerCase();let d=this.ba.get(a);
d||(d=[],this.ba.set(a,d));b.eg(d.length);b.mg(a);d.push(b);this.Fd(a)}Fd(a){let b=this.ra();const d=this.ba.get(a);if(d&&d.length){b=d[0].P();for(let g=0,n=d.length;g<n;++g){const q=d[g];g+1===n?q.S(this.ra()):q.S(d[g+1].P())}}for(const g of this.la(a))g.Le(b);this.ya&&this.Vc===a&&(this.ya.disconnect(),this.ya.connect(b))}yb(){return this.Uc}zb(){return this.na}dg(){this.Pd=!0}ye(a,b){return b?this.A.vg(a).then(d=>{const g=this.f.createBuffer(1,d.length,48E3);g.getChannelData(0).set(d);return g}):
new Promise((d,g)=>{this.f.decodeAudioData(a,d,g)})}ta(a){this.A.ta(a)}Ba(a){this.A.Ba(a)}pd(a){let b=0;for(let d=0,g=this.D.length;d<g;++d){const n=this.D[d];this.D[b]=n;n.L===a?n.c():++b}this.D.length=b}Me(){let a=0;for(let b=0,d=this.aa.length;b<d;++b){const g=this.aa[b];this.aa[a]=g;g.sa()?g.c():++a}this.aa.length=a}*la(a){if(a)for(const b of this.D)self.da.ze(b.Z,a)&&(yield b);else this.ga&&!this.ga.T()&&(yield this.ga)}async Eb(a,b,d,g,n){for(const q of this.aa)if(q.Ua()===b)return await U(q),
q;if(n)return null;g&&(this.Yc||this.Pd)&&this.Me();n="audio/webm; codecs=opus"===d&&!this.be;g&&n&&this.dg();a=!g||this.Yc||n?new self.te(this,a,b,d,g,n):new self.re(this,a,b,d,g);this.aa.push(a);await U(a);return a}async xc(a,b,d,g,n){for(const q of this.D)if(q.Ua()===b&&(q.hc()||n))return q.Oe(g),q;a=await this.Eb(a,b,d,n);g="html5"===a.Jc?new self.se(a.i,a,g):new self.ue(a.i,a,g);this.D.push(g);return g}Se(a){let b=this.qb.get(a);if(!b){let d=null;b={bd:0,Kg:new Promise(g=>d=g),resolve:d};this.qb.set(a,
b)}b.bd++}Wf(a){const b=this.qb.get(a);if(!b)throw Error("expected pending tag");b.bd--;0===b.bd&&(b.resolve(),this.qb.delete(a))}uc(a){a||(a=this.Td);return(a=this.qb.get(a))?a.Kg:Promise.resolve()}Fb(){if(0<this.Ga.size)M(this);else for(const a of this.D)if(a.md()){M(this);break}}Da(){for(var a of this.Ga)a.Da();a=this.jc();for(var b of this.D)b.Da(a);b=this.D.filter(d=>d.md()).map(d=>d.Ta());z(this,"state",{tickCount:this.Ud,audioInstances:b,analysers:[...this.Ga].map(d=>d.Be())});0===b.length&&
0===this.Ga.size&&this.Rb&&(this.A.Xf(this.ce),this.Rb=!1)}qc(a,b,d){z(this,"trigger",{type:a,tag:b,aiid:d})}async Sf(a){const b=a.originalUrl,d=a.url,g=a.type,n=a.isMusic,q=a.tag,v=a.isLooping,B=a.vol,D=a.pos,w=a.panning;let x=a.off;0<x&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+this.f.currentTime);this.Td=q;this.Se(q);try{this.ga=await this.xc(b,d,g,q,n),w?(this.ga.Bb(!0),this.ga.Ne(w.x,w.y,w.angle,
w.innerAngle,w.outerAngle,w.outerGain),w.hasOwnProperty("uid")&&this.ga.Pe(w.uid)):this.ga.Bb(!1),this.ga.Play(v,B,D,x)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.Wf(q)}M(this)}pg(a){a=a.tag;for(const b of this.la(a))b.ma()}qg(){for(const a of this.D)a.ma()}ig(a){const b=a.tag;a=a.paused;for(const d of this.la(b))a?d.Wa():d.Ab();this.Fb()}ng(a){const b=a.tag;a=a.vol;for(const d of this.la(b))d.Db(a)}async ef(a){const b=a.tag,d=a.vol,g=a.duration;
a=a.stopOnEnd;await this.uc(b);for(const n of this.la(b))n.Ae(d,g,a);this.Fb()}gg(a){this.Uc=a.vol;for(const b of this.D)b.Kb()}hg(a){const b=a.tag;a=a.isMuted;for(const d of this.la(b))d.qd(a)}kg(a){this.na=a.isSilent;this.A.Cb(this.na);for(const b of this.D)b.Jb()}fg(a){const b=a.tag;a=a.isLooping;for(const d of this.la(b))d.sc(a)}async jg(a){const b=a.tag;a=a.rate;await this.uc(b);for(const d of this.la(b))d.sd(a)}async Zf(a){const b=a.tag;a=a.pos;await this.uc(b);for(const d of this.la(b))d.rc(a)}async Tf(a){const b=
a.originalUrl,d=a.url,g=a.type;a=a.isMusic;try{await this.xc(b,d,g,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async tg(a){if(a=await this.Eb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.aa.indexOf(a),-1!==a&&this.aa.splice(a,1)}ug(){for(const a of this.aa)a.c();this.aa.length=0}lg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.tc(a);a&&this.f.suspend&&this.f.suspend()}Nf(a){this.dc=a.timeScale;this.Nc=a.gameTime;this.Ud=a.tickCount;if(0!==
this.$c)for(var b of this.D)b.Fa();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const g of this.D)g.fa===a&&g.rd(d.x,d.y,d.angle)}}async ud(a){var b=a.type;const d=a.tag;var g=a.params;if("filter"===b)g=new self.le(this,...g);else if("delay"===b)g=new self.je(this,...g);else if("convolution"===b){b=null;try{b=await this.Eb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",
n);return}g=new self.ie(this,b.$,...g);g.ag(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.me(this,...g);else if("phaser"===b)g=new self.oe(this,...g);else if("gain"===b)g=new self.ne(this,...g);else if("tremolo"===b)g=new self.qe(this,...g);else if("ringmod"===b)g=new self.pe(this,...g);else if("distortion"===b)g=new self.ke(this,...g);else if("compressor"===b)g=new self.he(this,...g);else if("analyser"===b)g=new self.ge(this,...g);else throw Error("invalid effect type");this.fe(d,
g);this.Ed()}cg(a){const b=a.index,d=a.param,g=a.value,n=a.ramp,q=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,g,n,q),this.Ed())}Vf(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const d of b)d.c();this.ba.delete(a);this.Fd(a)}}Re(a){this.Ga.add(a);this.Fb()}Uf(a){this.Ga.delete(a)}Ed(){this.Rc||(this.Rc=!0,Promise.resolve().then(()=>this.cf()))}cf(){const a={};for(const [b,d]of this.ba)a[b]=d.map(g=>g.Ta());z(this,"fxstate",{fxstate:a});this.Rc=!1}async Cf(a){const b=
a.saveLoadMode;if(3!==b)for(var d of this.D)d.sa()&&1===b||(d.sa()||2!==b)&&d.ma();for(const g of this.ba.values())for(const n of g)n.c();this.ba.clear();this.dc=a.timeScale;this.Nc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.na=a.isSilent;this.A.Cb(this.na);this.Uc=a.masterVolume;d=[];for(const g of Object.values(a.effects))d.push(Promise.all(g.map(n=>this.ud(n))));await Promise.all(d);await Promise.all(a.playing.map(g=>this.mf(g,b)));this.Fb()}async mf(a,b){if(3!==
b){var d=a.bufferOriginalUrl,g=a.bufferUrl,n=a.bufferType,q=a.isMusic,v=a.tag,B=a.isLooping,D=a.volume,w=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.xc(d,g,n,v,q)}catch(x){console.error("[Construct 3] Audio: error loading audio state: ",x);return}b.Je(a.pan);b.Play(B,D,w,0);a.isPlaying||b.Wa();b.Bc(a)}}}Ef(a,b){this.ya&&this.ya.disconnect();this.Vc=b.toLowerCase();this.ya=this.f.createMediaStreamSource(a);this.ya.connect(this.ld(this.Vc))}yf(){this.Nb||(this.Nb=this.f.createMediaStreamDestination(),
this.Ob.connect(this.Nb));return this.Nb.stream}static ze(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Qe(a){return a*f}static xe(a){return Math.pow(10,a/20)}static jd(a){return Math.max(Math.min(self.da.xe(a),1),0)}static Ie(a){return Math.log(a)/Math.log(10)*20}static He(a){return self.da.Ie(Math.max(Math.min(a,1),0))}static Fg(a,b){return 1-Math.exp(-b*a)}};self.Ca.Ra(self.da)}"use strict";function U(f){f.Ub||(f.Ub=f.Ac());return f.Ub}
self.ed=class{constructor(f,a,b,d,g){this.i=f;this.Bg=a;this.za=b;this.R=d;this.yg=g;this.Jc="";this.Ub=null}c(){this.Ub=this.i=null}Ac(){}W(){return this.i.W()}lc(){return this.Bg}Ua(){return this.za}kc(){return this.R}sa(){return this.yg}ea(){}};"use strict";
self.re=class extends self.ed{constructor(f,a,b,d,g){super(f,a,b,d,g);this.Jc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.kb=this.lb=null;this.J.addEventListener("canplaythrough",()=>!0);this.pb=this.W().createGain();this.nb=null;this.J.addEventListener("canplay",()=>{this.lb&&(this.lb(),this.kb=this.lb=null);!this.nb&&this.J&&(this.nb=this.W().createMediaElementSource(this.J),this.nb.connect(this.pb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.za}' error: `,n);this.kb&&(this.kb(n),this.kb=this.lb=null)})}c(){this.i.pd(this);this.pb.disconnect();this.pb=null;this.nb.disconnect();this.nb=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}Ac(){return new Promise((f,a)=>{this.lb=f;this.kb=a;this.J.src=this.za})}O(){return this.J}ea(){return this.J.duration}};"use strict";
async function V(f){if(f.wa)return f.wa;var a=f.i.A;if("cordova"===a.v&&a.nd(f.za)&&a.hb)f.wa=await a.wb(f.za);else{a=await fetch(f.za);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);f.wa=await a.arrayBuffer()}}async function W(f){if(f.$)return f.$;f.$=await f.i.ye(f.wa,f.Ag);f.wa=null}
self.te=class extends self.ed{constructor(f,a,b,d,g,n){super(f,a,b,d,g);this.Jc="webaudio";this.$=this.wa=null;this.Ag=!!n}c(){this.i.pd(this);this.$=this.wa=null;super.c()}async Ac(){try{await V(this),await W(this)}catch(f){console.error(`[Construct 3] Failed to load audio '${this.za}': `,f)}}ea(){return this.$?this.$.duration:0}};"use strict";
{let f=0;self.fd=class{constructor(a,b,d){this.i=a;this.L=b;this.Z=d;this.Lb=f++;this.M=this.W().createGain();this.M.connect(this.ra());this.B=null;this.ib=!1;this.ja=[0,0,0];this.ia=[0,0,0];this.H=!0;this.V=this.ka=this.G=!1;this.tb=1;this.Ha=!1;this.pa=1;a=this.i.$c;this.Sc=1===a&&!this.sa()||2===a;this.eb=this.fa=-1;this.ae=!1}c(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ra(){return this.i.ld(this.Z)}yb(){return this.i.yb()}xb(){return this.Sc?
this.i.Nc:performance.now()/1E3}lc(){return this.L.lc()}Ua(){return this.L.Ua()}kc(){return this.L.kc()}sa(){return this.L.sa()}Oe(a){this.Z=a}T(){}hc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}md(){return!this.H&&!this.T()}Aa(){}ea(){return this.L.ea()}Play(){}ma(){}Wa(){}Ab(){}Db(a){this.tb=a;this.M.gain.cancelScheduledValues(0);this.eb=-1;this.M.gain.value=this.mc()}Ae(a,b,d){if(!this.Ha){a*=this.yb();var g=this.M.gain;g.cancelScheduledValues(0);var n=this.i.jc();b=n+b;g.setValueAtTime(g.value,
n);g.linearRampToValueAtTime(a,b);this.tb=a;this.eb=b;this.ae=d}}Kb(){this.Db(this.tb)}Da(a){-1!==this.eb&&a>=this.eb&&(this.eb=-1,this.ae&&this.ma(),this.i.qc("fade-ended",this.Z,this.Lb))}mc(){const a=this.tb*this.yb();return isFinite(a)?a:0}qd(a){a=!!a;this.Ha!==a&&(this.Ha=a,this.Jb())}zb(){return this.i.zb()}Jb(){}sc(){}sd(a){this.pa!==a&&(this.pa=a,this.Fa())}Fa(){}rc(){}tc(){}Bb(a){a=!!a;this.ib!==a&&((this.ib=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.Wd,this.B.distanceModel=
this.i.Nd,this.B.refDistance=this.i.Xd,this.B.maxDistance=this.i.Vd,this.B.rolloffFactor=this.i.Zd),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ra())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ra())))}Ne(a,b,d,g,n,q){this.ib&&(this.rd(a,b,d),a=self.da.Qe,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(n),this.B.coneOuterGain=q)}rd(a,b,d){this.ib&&(this.ja[0]=a,this.ja[1]=b,this.ja[2]=0,this.ia[0]=Math.cos(d),this.ia[1]=Math.sin(d),this.ia[2]=0,this.B.setPosition(...this.ja),
this.B.setOrientation(...this.ia))}Pe(a){this.fa=a}nc(){}Le(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ta(){return{aiid:this.Lb,tag:this.Z,duration:this.ea(),volume:this.tb,isPlaying:this.IsPlaying(),playbackTime:this.Aa(),playbackRate:this.pa,uid:this.fa,bufferOriginalUrl:this.lc(),bufferUrl:"",bufferType:this.kc(),isMusic:this.sa(),isLooping:this.V,isMuted:this.Ha,resumePosition:this.nc(),pan:this.Ce()}}Bc(a){this.sd(a.playbackRate);this.qd(a.isMuted)}Ce(){if(!this.B)return null;const a=
this.B;return{pos:this.ja,orient:this.ia,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}Je(a){if(a){this.Bb(!0);a=this.B;var b=a.pos;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];b=a.orient;this.ia[0]=b[0];this.ia[1]=b[1];this.ia[2]=b[2];a.setPosition(...this.ja);a.setOrientation(...this.ia);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.fa=a.uid}else this.Bb(!1)}}}"use strict";
self.se=class extends self.fd{constructor(f,a,b){super(f,a,b);this.L.pb.connect(this.M);this.L.onended=()=>this.Cc()}c(){this.ma();this.L.pb.disconnect();super.c()}O(){return this.L.O()}Cc(){this.H=!0;this.fa=-1;this.i.qc("ended",this.Z,this.Lb)}T(){return this.O().ended}hc(){return this.H?!0:this.T()}Aa(){let f=this.O().currentTime;this.V||(f=Math.min(f,this.ea()));return f}Play(f,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==f&&(d.loop=f);this.Db(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Ua()}' to position '${b}': `,g)}this.i.ta(d);this.G=this.H=!1;this.V=f;this.pa=1}ma(){const f=this.O();f.paused||f.pause();this.i.Ba(f);this.H=!0;this.G=!1;this.fa=-1}Wa(){if(!(this.G||this.H||this.T())){var f=this.O();f.paused||f.pause();this.i.Ba(f);this.G=!0}}Ab(){!this.G||this.H||this.T()||(this.i.ta(this.O()),this.G=!1)}Jb(){this.O().muted=this.Ha||this.zb()}sc(f){f=!!f;this.V!==f&&
(this.V=f,this.O().loop=f)}Fa(){let f=this.pa;this.Sc&&(f*=this.i.dc);try{this.O().playbackRate=f}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${f}':`,a)}}rc(f){if(!this.H&&!this.T())try{this.O().currentTime=f}catch(a){console.warn(`[Construct 3] Error seeking audio to '${f}': `,a)}}nc(){return this.Aa()}tc(f){f?this.IsPlaying()?(this.O().pause(),this.ka=!0):this.ka=!1:this.ka&&(this.i.ta(this.O()),this.ka=!1)}};"use strict";
function X(f){f.j&&f.j.disconnect();f.j=null;f.$a=null}
self.ue=class extends self.fd{constructor(f,a,b){super(f,a,b);this.j=null;this.Xb=d=>this.Cc(d);this.Oc=!0;this.$a=null;this.N=this.Yb=this.Zb=0;this.Wc=1}c(){this.ma();X(this);this.Xb=null;super.c()}Cc(f){this.G||this.ka||f.target!==this.$a||(this.H=this.Oc=!0,this.fa=-1,X(this),this.i.qc("ended",this.Z,this.Lb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Oc}hc(){return!this.j||this.H?!0:this.T()}Aa(){let f;f=this.G?this.N:this.Yb+(this.xb()-this.Zb)*this.pa;this.V||(f=Math.min(f,this.ea()));
return f}Play(f,a,b,d){this.Wc=1;this.Db(a);X(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.$;this.j.connect(this.M);this.$a=this.j;this.j.onended=this.Xb;this.j.loop=f;this.j.start(d,b);this.G=this.H=this.Oc=!1;this.V=f;this.pa=1;this.Zb=this.xb();this.Yb=b}ma(){if(this.j)try{this.j.stop(0)}catch(f){}this.H=!0;this.G=!1;this.fa=-1}Wa(){this.G||this.H||this.T()||(this.N=this.Aa(),this.V&&(this.N%=this.ea()),this.G=!0,this.j.stop(0))}Ab(){!this.G||this.H||this.T()||(X(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.$a=this.j,this.j.onended=this.Xb,this.j.loop=this.V,this.Kb(),this.Fa(),this.j.start(0,this.N),this.Zb=this.xb(),this.Yb=this.N,this.G=!1)}mc(){return super.mc()*this.Wc}Jb(){this.Wc=this.Ha||this.zb()?0:1;this.Kb()}sc(f){f=!!f;this.V!==f&&(this.V=f,this.j&&(this.j.loop=f))}Fa(){let f=this.pa;this.Sc&&(f*=this.i.dc);this.j&&(this.j.playbackRate.value=f)}rc(f){this.H||this.T()||(this.G?this.N=f:(this.Wa(),this.N=f,this.Ab()))}nc(){return this.N}tc(f){f?
this.IsPlaying()?(this.ka=!0,this.N=this.Aa(),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.ka=!1:this.ka&&(X(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.$a=this.j,this.j.onended=this.Xb,this.j.loop=this.V,this.Kb(),this.Fa(),this.j.start(0,this.N),this.Zb=this.xb(),this.Yb=this.N,this.ka=!1)}Bc(f){super.Bc(f);this.N=f.resumePosition}};"use strict";
{class f{constructor(a){this.i=a;this.f=a.W();this.Qd=-1;this.R=this.Z="";this.g=null}c(){this.f=null}eg(a){this.Qd=a}mg(a){this.Z=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,d,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var n=this.f.currentTime;g+=n;switch(d){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,g)}}}Ta(){return{type:this.R,tag:this.Z,params:this.g}}}
self.le=class extends f{constructor(a,b,d,g,n,q,v){super(a);this.R="filter";this.g=[b,d,g,n,q,v];this.l=this.o();this.b=this.o();this.b.gain.value=v;this.a=this.o();this.a.gain.value=1-v;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=d;this.u.detune.value=g;this.u.Q.value=n;this.u.gain.vlaue=q;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,d,g);break;case 2:this.g[2]=b;this.m(this.u.detune,b,d,g);break;case 3:this.g[3]=b;this.m(this.u.Q,b,d,g);break;case 4:this.g[4]=b,this.m(this.u.gain,b,d,g)}}};self.je=class extends f{constructor(a,b,d,g){super(a);this.R="delay";this.g=[b,d,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.mb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.cb=this.o();this.cb.gain.value=d;this.l.connect(this.mb);this.l.connect(this.a);this.mb.connect(this.b);this.mb.connect(this.U);this.U.connect(this.cb);this.cb.connect(this.mb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.mb.disconnect();this.U.disconnect();this.cb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){const n=self.da.jd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 4:this.g[1]=n(b);this.m(this.cb.gain,n(b),d,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,g)}}};self.ie=class extends f{constructor(a,b,d,g){super(a);this.R="convolution";this.g=[d,g];this.Ld=this.Kd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.bb=this.f.createConvolver();this.bb.normalize=d;this.bb.buffer=b;this.l.connect(this.bb);this.l.connect(this.a);this.bb.connect(this.b)}c(){this.l.disconnect();this.bb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}ag(a,b){this.Kd=a;this.Ld=b}Ta(){const a=
super.Ta();a.bufferOriginalUrl=this.Kd;a.bufferUrl="";a.bufferType=this.Ld;return a}};self.me=class extends f{constructor(a,b,d,g,n,q){super(a);this.R="flanger";this.g=[b,d,g,n,q];this.l=this.o();this.a=this.o();this.a.gain.value=1-q/2;this.b=this.o();this.b.gain.value=q/2;this.fb=this.o();this.fb.gain.value=n;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.I=this.o();this.I.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.fb);this.fb.connect(this.U);this.s.connect(this.I);this.I.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.fb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,d,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,d,g);break;case 8:this.g[3]=b/100,this.m(this.fb.gain,b/100,d,g)}}};self.oe=class extends f{constructor(a,b,d,g,n,q,v){super(a);this.R="phaser";this.g=[b,d,g,n,q,v];this.l=this.o();this.a=this.o();this.a.gain.value=1-v/2;this.b=this.o();this.b.gain.value=v/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
d;this.u.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=q;this.I=this.o();this.I.gain.value=n;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.I);this.I.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,d,g);break;case 2:this.g[1]=b;this.m(this.u.detune,b,d,g);break;case 3:this.g[2]=b;this.m(this.u.Q,b,d,g);break;case 6:this.g[3]=b;this.m(this.I.gain,b,d,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,d,g)}}};self.ne=class extends f{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){const n=self.da.jd;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,g)}}};self.qe=class extends f{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.I=this.o();this.I.gain.value=d/2;this.s.connect(this.I);this.I.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,g);this.m(this.I.gain,b/2,d,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,g)}}};self.pe=class extends f{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.sb=this.o();this.sb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.sb.gain);this.s.start(0);this.l.connect(this.sb);this.l.connect(this.a);this.sb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.sb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,g);
this.m(this.a.gain,1-b,d,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,g)}}};self.ke=class extends f{constructor(a,b,d,g,n,q){super(a);this.R="distortion";this.g=[b,d,g,n,q];this.l=this.o();this.ac=this.o();this.$b=this.o();this.bg(g,n);this.b=this.o();this.b.gain.value=q;this.a=this.o();this.a.gain.value=1-q;this.ec=this.f.createWaveShaper();this.Lc=new Float32Array(65536);this.gf(b,d);this.ec.curve=this.Lc;this.l.connect(this.ac);this.l.connect(this.a);this.ac.connect(this.ec);this.ec.connect(this.$b);
this.$b.connect(this.b)}c(){this.l.disconnect();this.ac.disconnect();this.ec.disconnect();this.$b.disconnect();this.b.disconnect();this.a.disconnect();super.c()}bg(a,b){.01>a&&(a=.01);this.ac.gain.value=a;this.$b.gain.value=Math.pow(1/a,.6)*b}gf(a,b){for(let d=0;32768>d;++d){let g=d/32768;g=this.og(g,a,b);this.Lc[32768+d]=g;this.Lc[32768-d-1]=-g}}og(a,b,d){d=1.05*d*b-b;const g=0>a?-a:a;return(g<b?g:b+d*self.da.Fg(g-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}};self.he=class extends f{constructor(a,b,d,g,n,q){super(a);this.R="compressor";this.g=[b,d,g,n,q];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=g;this.h.attack.value=n;this.h.release.value=q}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.ge=class extends f{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Od=new Float32Array(this.h.frequencyBinCount);this.$d=new Uint8Array(b);this.Yd=this.Ka=0;this.i.Re(this)}c(){this.i.Uf(this);this.h.disconnect();super.c()}Da(){this.h.getFloatFrequencyData(this.Od);this.h.getByteTimeDomainData(this.$d);const a=this.h.fftSize;let b=this.Ka=0;for(var d=0;d<a;++d){let g=(this.$d[d]-128)/128;0>g&&(g=-g);
this.Ka<g&&(this.Ka=g);b+=g*g}d=self.da.He;this.Ka=d(this.Ka);this.Yd=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Be(){return{tag:this.Z,index:this.Qd,peak:this.Ka,rms:this.Yd,binCount:this.h.frequencyBinCount,freqBins:this.Od}}}}"use strict";async function aa(f,a){a=a.type;let b=!0;0===a?b=await ba():1===a&&(b=await ca());z(f,"permission-result",{type:a,result:b})}
async function ba(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request orientation permission: ",f),!1}}
async function ca(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request motion permission: ",f),!1}}self.Ca.Ra(class extends self.Sa{constructor(f){super(f,"touch");J(this,"request-permission",a=>aa(this,a))}});"use strict";function Y(f,a,b){Z(f,a,URL.createObjectURL(new Blob([b.html],{type:"text/html"})));f.Sb=!0}
function Z(f,a,b){a.src.startsWith("blob:")&&f.Sb&&URL.revokeObjectURL(a.src);a.src=b}
self.Ca.Ra(class extends self.we{constructor(f){super(f,"iframe");this.Sb=!1;Q(this,"navigate-url",(a,b)=>{Z(this,a,b.url);this.Sb=!1});Q(this,"display-html",(a,b)=>Y(this,a,b))}hd(f){const a=document.createElement("iframe");a.style.position="absolute";a.style.border="none";var b=navigator.userAgent;/iphone|ipad|ipod/i.test(b)&&(b=/(iphone\s+os|ipad[^)]*os)\s+([0-9_]+)/i.exec(b),b=parseInt(b[b.length-1]),12>=b||isNaN(b))&&(a.setAttribute("noresize","noresize"),a.setAttribute("scrolling","no"));f.isVisible||
(a.style.display="none");f.id&&(a.id=f.id);f.allow&&(a.setAttribute("allow",f.allow),f.allow.includes("fullscreen")&&a.setAttribute("allowfullscreen",""));f.enableSandbox&&a.setAttribute("sandbox",f.sandbox);f.url?a.src=f.url:f.html&&Y(this,a,f);return a}td(){}kd(f){Z(this,f,"");this.Sb=!1}});
